### ISSUE TITLE
Output variable value in the email report

### ISSUE THREAD

**Issue by ChandruD103** [Ginger-Automation/Ginger#1092] opened 2019-07-19 15:46 UTC
**Describe the bug**
Created the runner set and trying to get provide a variable's value as part of report. But unable to use the variable. Always in the email report "ERROR: The Variable 'Thrhold' was not found" 

**To Reproduce**
1. Create a businessflow with a variable(V1) value that got assigned by one of the actions in the activity.
2. Have the  variable(V1) to get linked with a Variable(v2) here"Thrhold" defined in the runner setup as part of comments section of the email. 
3. Execute the runner in the cmd **C:\Users\xxx596>D:\Ginger\Debug\Ginger.exe ConfigFile="D:\Ginger\Documents\RunSetShortCuts\eGain-eGain.Ginger.AutoRunConfigs.Config**"
4. Error in the email report ERROR: The Variable 'Thrhold' was not found

**Expected behavior**
Threshold value crossed, the count is 25

**Screenshots**
![image](https://user-images.githubusercontent.com/25457464/61547942-73316780-aa1a-11e9-8a1a-49c28e84aa81.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser   chrome

**Comment by sudarshan0212** [comment] 2019-09-19 13:28
Hi Chandru,

1. Please specify on which ginger version you were able to reproduce this issue. 
2. Also specify which type of variable you were using like Global / Businessflow / Activity level. 

I tried above scenario with below steps on latest ginger version and its working fine. 
1. Created businessflow. 
2. Added one businessflow level string variable (V1).
3. Added one Global Variable(V2). 
4. Linked variable V1 to V2.  
5. Added one set variable action and assigned some value to V1. 
6. Created runset and added above flow in it. 
7. Added runset send email action in runset. 
8. Used V2 variable in comment section of runset email action. 

P.S : We can use only global variables in runset email action.

**Comment by MeniKadosh1** [comment] 2019-10-12 18:25
closing it due to lack of respond.

**Closed by MeniKadosh1** 2019-10-12 18:25 UTC
